name: PUSH

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        name: "Checking out."

      - name: Run Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: '*.yaml'
          cliArguments: '--schema-version 1.20.0'
